Repository EATMOJI-DionysOS/Eatmoji_BE, pull requests merged in 2025-06, with the labels that each got.

#18 Fix/SecurityConfig now accepts all the request
  src/main/java/com/DionysOS/Eatmoji/config/SecurityConfig.java
Labels: 🔨fix, 민규

#22 Feat/#17 API Recommendation History (On Progress)
  Fast_API_GPT/Get_Recommendation_API.py
  src/main/java/com/DionysOS/Eatmoji/controller/HistoryController.java
  src/main/java/com/DionysOS/Eatmoji/controller/RecommendController.java
  src/main/java/com/DionysOS/Eatmoji/model/History.java
  src/main/java/com/DionysOS/Eatmoji/service/GptRecommendation.java
  src/main/resources/test2.http
  src/test/java/com/DionysOS/Eatmoji/repository/HistoryRepositoryTest.java
Labels: ✨feat, 민규

#23 Feat/#15 api gpt personalized
  Fast_API_GPT/Get_Recommendation_API.py
  Fast_API_GPT/personalized_gpt_api.py
  src/main/java/com/DionysOS/Eatmoji/controller/RecommendController.java
  src/main/java/com/DionysOS/Eatmoji/dto/EmotionRequest.java
  src/main/java/com/DionysOS/Eatmoji/dto/PersonalizedRequest.java
  src/main/java/com/DionysOS/Eatmoji/model/User.java
  src/main/java/com/DionysOS/Eatmoji/repository/HistoryRepository.java
  src/main/java/com/DionysOS/Eatmoji/service/GptRecommendation.java
Labels: ✨feat, 진하

#28 Fix/#27 Depolyment Bug Fix
  .github/workflows/deploy.yml
Labels: 🔨fix, 준섭

#29 Fix/#27 Depolyment Bug Fix
  src/main/resources/application.yml
Labels: 🔨fix, 민규

#31 Fix/#27 환경변수 할당 우선순위 설정
  .github/workflows/deploy.yml
Labels: 🔨fix, 준섭

#32 Fix/#27 DB 배포 수정
  .github/workflows/deploy.yml
  src/main/resources/application.yml
Labels: 🔨fix, 준섭

#33 Fix/#27 스크립트 명령어 처리 분리
  .github/workflows/deploy.yml
Labels: 🔨fix, 준섭

#37 Config/#35 api swagger
  build.gradle
  src/main/resources/application.yml
Labels: 🔧 config, 진하

#39 Fix/#27 자동 배포 처리 버그 수정
  .github/workflows/deploy.yml
Labels: 🔨fix, 준섭

#40 Fix/#27 서버 재시작 스크립트 분리
  .github/workflows/deploy.yml
Labels: 🔨fix, 준섭

#41 Refactor/#38 api integrate gpt
  Fast_API_GPT/emoji_recommend.py
  Fast_API_GPT/main.py
  Fast_API_GPT/personalized_recommend.py
Labels: ♻️ refactor, 진하

#44 Fix/#43 User Profile NULL fix
  src/main/java/com/DionysOS/Eatmoji/model/User.java
  src/main/java/com/DionysOS/Eatmoji/service/UserService.java
Labels: 🔨fix, 민규

#45 Fix/#43 Profile NULL fix - Getter improved
  src/main/java/com/DionysOS/Eatmoji/model/User.java
Labels: 🔨fix, 민규

#48 Feat/#47 Cors Configuration
  src/main/java/com/DionysOS/Eatmoji/config/CorsConfig.java
  src/main/java/com/DionysOS/Eatmoji/config/SecurityConfig.java
Labels: ✨feat, 준섭

#57 Fix/ Authentication Token
  Fast_API_GPT/emoji_recommend_login.py
  src/main/java/com/DionysOS/Eatmoji/config/JwtAuthFilter.java
  src/main/java/com/DionysOS/Eatmoji/config/SecurityConfig.java
  src/main/java/com/DionysOS/Eatmoji/service/GptRecommendation.java
  src/main/java/com/DionysOS/Eatmoji/service/JwtTokenProvider.java
Labels: 🔨fix, 민규

#64 Fix/ Connection security Fixation
  src/main/java/com/DionysOS/Eatmoji/config/SecurityConfig.java
Labels: 🔨fix, 민규

#67 fix/ #66 application.yml modification
  src/main/resources/application.yml
Labels: 🔨fix, 민규

#76 fix: 배포시 자동으로 파일 덮어쓰도록 설정 추가 #27
  .github/workflows/deploy.yml
Labels: 🔨fix, 진하, 준섭

#77 fix: 배포시 파일 삭제 후 다시 넣도록 설정 추가 #27
  .github/workflows/deploy.yml
Labels: 🔨fix, 진하, 준섭

#79 Fix/#27 ec2 내부 빌드 파일의 위치 수정
  .github/workflows/deploy.yml
Labels: 🔨fix, 준섭

#83 Fix/ Exception handling in HistoryService and GptRecommendation
  Fast_API_GPT/emoji_recommend.py
  Fast_API_GPT/emoji_recommend_login.py
  Fast_API_GPT/main.py
  Fast_API_GPT/personalized_recommend.py
  src/main/java/com/DionysOS/Eatmoji/service/GptRecommendation.java
  src/main/java/com/DionysOS/Eatmoji/service/HistoryService.java
Labels: 🔨fix, 🐛 bug, 민규

#85 Fix/ User email JWT fix
  src/main/java/com/DionysOS/Eatmoji/model/History.java
  src/main/java/com/DionysOS/Eatmoji/service/UserService.java
Labels: 🔨fix, 🐛 bug, 민규

#86 Refactor/#72 api personalized response
  src/main/java/com/DionysOS/Eatmoji/service/GptRecommendation.java
Labels: ♻️ refactor, 진하

#89 Fix/#88 api emoji and prompt
  Fast_API_GPT/change_to_json.py
  Fast_API_GPT/emoji2emotion_filtered_baseintensity.json
  Fast_API_GPT/emoji_recommend.py
  Fast_API_GPT/emoji_recommend_login.py
  Fast_API_GPT/personalized_recommend.py
Labels: 🔨fix, 진하
